# Generated by Django 3.1.6 on 2021-02-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_baby_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='changing date')),
                ('diaper', models.CharField(choices=[('1', 'No. ONE'), ('2', 'No. TWO')], default='1', max_length=1)),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.baby')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
