# Generated by Django 3.1.6 on 2021-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_changing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changing',
            name='diaper',
            field=models.CharField(choices=[('1', 'No. One'), ('2', 'No. Two')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='feeding',
            name='meal',
            field=models.CharField(choices=[('M', 'Moms Milk'), ('F', 'Formula')], default='M', max_length=1),
        ),
    ]
